### ISSUE TITLE
Intended change to CORS policy?

### ISSUE THREAD

**Issue by rsarvar1a** [949mac/846-backend#2]
Access-Control-Allow-Origin now only allows https://frontend-1750f.web.app/ although this change isn't reflected in the repo, is it intended? This makes it a little bit tough to develop locally over at https://github.com/mnlmaier/846-frontend.

**Comment by MikeCraig418** [comment]
@rsarvar1a  -- are you on `https://api.846policebrutality.com/api/incidents`? I recall adding a staging link to an issue in the front-end repo.

https://api.846policebrutality.com/api/incidents and
https://api.846policebrutality.com/api/incidents?include=evidence is cached onto a CDN to allow for unlimited throughput, caching, hits, etc.

The CDN should have CORS disabled.

Let me know!

**Comment by rsarvar1a** [comment]
Yep, I'm using https://api.846policebrutality.com/api/incidents locally - getting back errors even after Empty Cache + Hard Reload. I had no issues around 4-5 hours ago, haven't touched a single line of code for the request either so I've got no clue what's going on.

**Comment by MikeCraig418** [comment]
Will you try once more? Be sure to clear the cache.

**Comment by MikeCraig418** [comment]
Also, are you having issues via `localhost`?

**Comment by MikeCraig418** [comment]
Let me know how i can support. I did change somethings on the browser cache level but it looks pretty good to me:

![image](https://user-images.githubusercontent.com/23151962/83903757-8a9d4000-a713-11ea-88c5-dddd74612d47.png)

Note: I threw the endpoint URL into an older build I had

**Comment by rsarvar1a** [comment]
Busted my cache a few times, probably coincided with whatever you did, but it's working now, thanks a bunch!

**Comment by MikeCraig418** [comment]
No problem. Thanks for letting me know.
