### ISSUE TITLE
QueryException when using the Evidence API

### ISSUE THREAD

**Issue by rsarvar1a** [949mac/846-backend#3]
`curl https://api.846policebrutality.com/api/incidents?include=evidence` is non-functional:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'videos.evidence_id' in 'where clause' (SQL: select * from 'videos' where 'videos'.'evidence_id' in (0, 0, 0 ...) and 'videos'.'deleted_at' is null)`

**Comment by MikeCraig418** [comment]
Thanks. Let me check this out now!

**Comment by MikeCraig418** [comment]
@rsarvar1a back online
