### ISSUE TITLE
Question about the response JSON structure and API service

### ISSUE THREAD

**Issue by hossain-khan** [949mac/846-backend#6]
Hey @949mac kudos for putting time to make this API possible. I am working on a front end client [Android app](https://github.com/amardeshbd/android-police-brutality-incidents) using same [data source](https://github.com/2020PB/police-brutality).

```json
{
  "id":"7b05ac80-a9d6-11ea-a72a-db8cd82c4def",
  "pb_id":"ut-saltlakecity-4",
  "state":"Utah",
  "city":"Salt Lake City",
  "date":"2020-05-30T00:00:00.000000Z",
  "title":"Police shoot tear gas canister at man from close range, striking him in the chest",
  "description":null,
  "links":[
    "https:\/\/twitter.com\/greg_doucette\/status\/1268333029526843392",
    "https:\/\/www.instagram.com\/p\/CA148-0B14t6mQZqJZYzwq25KdoPzZ5CJmV3oQ0\/"
  ],
  "data":null,
  "geocoding":{
    "lat":"40.7607793",
    "long":"-111.8910474"
  }
}
```

I'm deciding between using plain [raw data](https://raw.githubusercontent.com/2020PB/police-brutality/data_build/all-locations.json) and the API exposed by api.846policebrutality.com

I see some differences between the `all-locations.json` data and API response, I just wanted to confirm few things.

1. The `"id":"7b05ac80-a9d6-11ea-a72a-db8cd82c4def"` is likely system auto-generated. Is it going to be stay consistent after each data import? or it will generate new set of keys?
1. I see you have thought of future and added `"description":null` - I am guessing this will stay as null until there is way to manually update them for each item.
1. What is the purpose of `"data":null` field?
1. Where is `"geocoding": {}` data coming from? it's not in the original source.

Also, wondering where is the ` api.846policebrutality.com` hosted and how long will it stay live? I am sure there is cost associated with it.

**Comment by MikeCraig418** [comment]
Hello, thanks for coming by! 

> I'm deciding between using plain raw data and the API exposed by api.846policebrutality.com
This API should allow you to deliver a better experience to the end user. You should be able to pull only the information you need. For mobile, this can play a huge role.

For example, if you want to perform back-end filter by state, or date, you can do this easily. For example, this request is only 15kb:
![image](https://user-images.githubusercontent.com/23151962/84213236-ff0a1300-aa74-11ea-8f9e-1e87e01dbef5.png)


> id":"7b05ac80-a9d6-11ea-a72a-db8cd82c4def" is likely system auto-generated. Is it going to be stay consistent after each data import? or it will generate new set of keys?

My ID might change, but its not to likely. They have been pretty stable for the past few days. 

> I see you have thought of future and added "description":null - I am guessing this will stay as null until there is way to manually update them for each item.

That is correct. You can ignore this field for now. Check this issue https://github.com/2020PB/police-brutality/issues/504 for changes to API structure.

> What is the purpose of "data":null field?

Originally I was expected to pull in some additional information from the main feed. You can ignore this field, and it will probably be dropped sometime.

> Where is "geocoding": {} data coming from? it's not in the original source.

I fetch it from Google. Check it out: https://github.com/949mac/846-backend/blob/develop/app/Console/Commands/UpdateLatLong.php

> Also, wondering where is the api.846policebrutality.com hosted and how long will it stay live? I am sure there is cost associated with it.

I will keep this service online indefinitely. If it becomes cost prohibitive to stay online, I'll give you and everyone else plenty of notice. But right now, there is no plan to retire the endpoint at any time!

**Comment by hossain-khan** [comment]
Thanks a lot for taking the time and answering them, this helps a lot 🙏

**Comment by hossain-khan** [comment]
Hey Mike, just FYI I have finished integrating with the API. It's working very nicely. 😄 

<img width="40%" src="https://user-images.githubusercontent.com/99822/84328489-1964ef00-ab50-11ea-9fdd-02c48efea0b7.gif">
