### ISSUE TITLE
Question about geolocation data

### ISSUE THREAD

**Issue by nicktahani** [949mac/846-backend#8]
Hi, I see that the geolocation values reflect those of the city in which the incident occurred, and not the exact location. However, I noticed that one of the featured web apps (https://846policebrutality.com/) in this repo does in fact contain exact locations. Is that data being sourced from somewhere in this repo? 

Thanks for all of your hard work!

**Comment by MikeCraig418** [comment]
Hi @nicktahani, I work directly with that team. They are in fact using this API.

I recall that team making some tweaks to some errant markers, but nothing too major. I briefly looked at their source code (https://github.com/mnlmaier/846-frontend/) -- but let me ask that team for you. Hang tight!

**Comment by MikeCraig418** [comment]
@nicktahani, I confirmed -- the front end guys added a little bit of disparity, or "noise" to slightly randomize the geo-coordinates to keep them close but prevent them from stacking on top of each other.

Here's some more details on how they did that:

https://github.com/mnlmaier/846-frontend/search?q=noise&unscoped_q=noise

**Comment by nicktahani** [comment]
@949mac ahh ok I got it, that makes sense. Thank you so much for taking the time to answer my question!
