### ISSUE TITLE
Composer install failing without Laravel Nova

### ISSUE THREAD

**Issue by jdlugo** [949mac/846-backend#9]
Love the project and would like to contribute but I ran into some issues getting started.

I have tried cloning the repo and following the setup instructions, however, I don't have an actively licensed Laravel Nova account. As the directions indicate, I removed references to Laravel Nova and associated dependencies however the application won't seem to start without them. Any insight you could offer or do I need a licensed copy of Laravel Nova?

**Comment by MikeCraig418** [comment]
Hi @jdlugo - 

I totally understand this! I'm sorry you had an issue. The API component can be built without Laravel Nova, as we use Laravel Nova for some other backend admin-related tasks.

Perform `git clone` and then remove the laravel/nova line from the `composer.json` file. It should build for you!

**Comment by MikeCraig418** [comment]
One more note: Be sure to read https://github.com/949mac/846-backend#developer-notes. I've included some additional information on the build process.

**Comment by jdlugo** [comment]
Thank you for your response!

It seems like I also need to remove the Laravel Nova object from the `repositories` portion of the composer file.  Except I get this error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for optimistdigital/nova-notes-field ^1.5 -> satisfiable by optimistdigital/nova-notes-field[1.5.0].
    - optimistdigital/nova-notes-field 1.5.0 requires laravel/nova ^2.0.11 || ^3.0 -> no matching package found.
  Problem 2
    - maatwebsite/laravel-nova-excel 1.2.x-dev requires laravel/nova * -> no matching package found.
    - maatwebsite/laravel-nova-excel 1.2.1 requires laravel/nova * -> no matching package found.
    - maatwebsite/laravel-nova-excel 1.2.0 requires laravel/nova * -> no matching package found.
    - Installation request for maatwebsite/laravel-nova-excel ^1.2 -> satisfiable by maatwebsite/laravel-nova-excel[1.2.0, 1.2.1, 1.2.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by jdlugo** [comment]
If it's easier to just buy/setup Laravel Nova, I can go ahead and do that...don't want to cause you too much time resolving my env setup.

**Comment by MikeCraig418** [comment]
> If it's easier to just buy/setup Laravel Nova, I can go ahead and do that...don't want to cause you too much time resolving my env setup.

Totally. It's a great platform! I absolutely love it and it's unfortunate it isn't entirely free. But it's well worth the $$ if you have the means.
